language: node_js
dist: bionic
node_js:
- '10'
cache:
  directories:
  - "~/.cache"
before_install:
- npm install --global lerna
install:
- node ./run.js
script:
- lerna run test
- ./packages/ui/scripts/build-storybook.sh
notifications:
  slack:
    secure: n3QwBUoZ2dl3gncWboBPFWHJVbxGxmjUABWx+dvBjA1864Hqh5WUTuVUfJcbrB6sQDZ1U1fDXQFkvgQsULqRtBO+QHfqdU/X7W8qome7oOzcxLaOFLvFyxtMINRNBf8hlQ5qPq5VwP49ZX9wSB9mFxpmqQCml4G+Tzqr7uzfxMwfSINGpP5ll81E+jbY8WWifUmzul+eTzktDgh4uTHABF7CubyvRPMNGeXXKUU/8PW9VB7nX7PUQ7Supm031M/+QIJj85UM0i00H8c3ctm2kjXSGzKUVNETZ24pLM3F3f7l84AOEk9SItxD/zIG6s/s2SQp07HYX4dSHLk5CyewsS73twAruK48vpkNxvj4W0PPoLR8AUpcwhsH5GMMKLXbLUSKjOWVD9IzwljAHccchRJ5dALeRXsdCGbBO1XhrEMrXFA5OgoXQgLgMyltiZ4sINIdBriKbCneE8XCaOAQsL651HvMdeVBrOsjw8kUXx4UOJMT1CDf/sErt+F97326nGq4SnSuKQpnQpAPjuL1e+/Vxc38ddFPBQaf/ElfF0o16/HDnXyjPn7fqChL/28SESqXvIb3WHfcB60vogg2VkMLrqEVVP3B1/gT7E7i9YMQ4cRQ2z5v1+VrJVLbBGPpa78ggVG9N84dNDgQB2jPCb4hIYDx+nRufk2w95n3pPc=
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  local_dir: ./packages/ui/storybook-static
  on:
    branch: master
